export type DomEventType =
  "onabort" |
  "onanimationcancel" |
  "onanimationend" |
  "onanimationiteration" |
  "onauxclick" |
  "onblur" |
  "oncancel" |
  "oncanplay" |
  "oncanplaythrough" |
  "onchange" |
  "onclick" |
  "onclose" |
  "oncontextmenu" |
  "oncuechange" |
  "ondblclick" |
  "ondurationchange" |
  "onended" |
  "onerror" |
  "onfocus" |
  "ongotpointercapture" |
  "oninput" |
  "oninvalid" |
  "onkeydown" |
  "onkeypress" |
  "onkeyup" |
  "onload" |
  "onloadeddata" |
  "onloadedmetadata" |
  "onloadend" |
  "onloadstart" |
  "onlostpointercapture" |
  "onmousedown" |
  "onmouseenter" |
  "onmouseleave" |
  "onmousemove" |
  "onmouseout" |
  "onmouseover" |
  "onmouseup" |
  "onpause" |
  "onplay" |
  "onpointercancel" |
  "onpointerdown" |
  "onpointerenter" |
  "onpointerleave" |
  "onpointermove" |
  "onpointerout" |
  "onpointerover" |
  "onpointerup" |
  "onreset" |
  "onresize" |
  "onscroll" |
  "onselect" |
  "onselectionchange" |
  "onselectstart" |
  "onsubmit" |
  "ontouchcancel" |
  "ontouchstart" |
  "ontransitioncancel" |
  "ontransitionend" |
  "onwheel";
