export {applyDomDiffDel} from "./applyDomDiffDel";
export {applyDomDiffSet} from "./applyDomDiffSet";
export {applyDomDiff} from "./applyDomDiff";
export {delDomProp} from "./delDomProp";
export {fetchDomParent2} from "./fetchDomParent2";
export {fetchDomParent} from "./fetchDomParent";
export {getDomParent} from "./getDomParent";
export {getDomProp} from "./getDomProp";
export {setDomProp} from "./setDomProp";
